server:
  port: ${env.server.port}
  servlet:
    contextPath: /api
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:/env.yml
  servlet:
    multipart:
      max-file-size: ${env.file.uploadSize}
      max-request-size: ${env.file.uploadSize}
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${env.db.host}:${env.db.port}/${env.db.name}?autoReconnect=true
    username: ${env.db.user}
    password: ${env.db.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${env.redis.host}
    port: ${env.redis.port}
    database: ${env.redis.database}
logging:
  level:
    web: DEBUG
  org:
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          BasicBinder: TRACE
