server:
  servlet:
    contextPath: /api
spring:
  servlet:
    multipart:
      max-file-size: ${FILE_UPLOAD_SIZE}
      max-request-size: ${FILE_UPLOAD_SIZE}
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DB}
---
jwt:
  secret-key: ${JWT_SECRET_KEY}
  time:
    token: ${JWT_ACCESS_TOKEN_ALIVE_TIME}
    refresh-token: ${JWT_REFRESH_TOKEN_ALIVE_TIME}
cookie:
  domain:
  secure: ${COOKIE_SECURE}
  name:
    token: ${ACCESS_TOKEN_COOKIE_NAME}
    refresh-token: ${REFRESH_TOKEN_COOKIE_NAME}
  same-site: ${COOKIE_SAME_SITE}
file:
  path:
    base: ${FILE_BASE_PATH}
    upload:
      board: ${BOARD_FILE_UPLOAD_PATH}
      emoticon: ${EMOTICON_UPLOAD_PATH}
oauth:
  bsm:
    client:
      id: ${BSM_AUTH_CLIENT_ID}
      secret: ${BSM_AUTH_CLIENT_SECRET}
web-push:
  key:
    public: ${WEB_PUSH_PUBLIC_KEY}
    private: ${WEB_PUSH_PRIVATE_KEY}
api:
  meal:
    url: ${NEIS_MEAL_API_URL}
meal:
  url: https://bssm.app/meal
timetable:
  url: https://bssm.app/timetable
